version: '3.4'
services:
  
  dirmod-cotizador-app:
    ports:
     - "5000:80"   
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - CORS=http://localhost:8080

  dirmod-cotizador-web:
    ports:
     - "8080:80"
    environment: 
     - VUE_APP_SERVER_URL=http://localhost:5000