version: '3.4'
services:

  dirmod-cotizador-app:
    image: dirmod-cotizador-app:${TAG:-latest}
    build: 
      context: .
      dockerfile: ./Dirmod.Cotizador.Application/Dockerfile
  
  dirmod-cotizador-web:
      image: dirmod-cotizador-web:${TAG:-latest}
      build: 
        context: ./Dirmod.Cotizador.WebApp
        dockerfile: ./Dockerfile
      depends_on:
       - dirmod-cotizador-app